### Upload PDF
POST https://10.0.0.89:7296/api/Pdfs
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Event Anleitung
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Wichtige Informationen zum Event
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< ./test-documents/test.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Liste aller PDFs
GET https://10.0.0.89:7296/api/Pdfs

### Hole ein PDF
GET https://10.0.0.89:7296/api/Pdfs/1
